### ISSUE TITLE
Question about executing the source code

### ISSUE THREAD

**Issue by avarbykira** [Kiriki-liszt/Sky_Blue_EQ4#4]
Hi, 

Is the code in folder `source` intact and executable in IDEs like CLion? I am trying to modify some details of the plugin, but I am new to C++. After cloning the repo I find there is no place to execute the code. I would appreciate if you could help me with this problem.

Cheers

**Comment by Kiriki-liszt** [comment]
Hello!
Thanks for checking out my plugin and sorry for late reply.

This project uses VSTSDK and CMAKE to build, so you can build it in CLI or make a VS project with it.
It's described in VSTSDK manual very well. 

If you are new to CMAKE or sth like these, you can use VSTSDK's project starter exe.
It comes with VSTSDK, and lets you to configure to IDEs it supports.
After that, you can copy and paste the codes to your project.
However, to keep it connected to Git(so you can push/pull to my project), it's better to use CMAKE and make your own VS project with it.

Have a nice day!
